// <auto-generated />
using System;
using CarStoreApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarStoreApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarStoreApi.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "red",
                            CreatedDate = new DateTime(2025, 1, 18, 13, 31, 30, 826, DateTimeKind.Local).AddTicks(9251),
                            ImageUrl = "https://img.freepik.com/premium-photo/photo-supper-shine-bmw-series-stylish-design_1025753-53043.jpg?w=360",
                            Model = "BMW",
                            Name = "Foo",
                            Price = 3000m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Color = "black",
                            CreatedDate = new DateTime(2025, 1, 18, 13, 31, 30, 826, DateTimeKind.Local).AddTicks(9290),
                            ImageUrl = "https://img.freepik.com/premium-photo/photo-supper-shine-bmw-series-stylish-design_1025753-52982.jpg?w=996",
                            Model = "Mercedes",
                            Name = "Foo",
                            Price = 5500m,
                            UpdatedDate = new DateTime(2025, 1, 18, 13, 31, 30, 826, DateTimeKind.Local).AddTicks(9292)
                        },
                        new
                        {
                            Id = 3,
                            Color = "bluce",
                            CreatedDate = new DateTime(2025, 1, 18, 13, 31, 30, 826, DateTimeKind.Local).AddTicks(9294),
                            ImageUrl = "https://img.freepik.com/premium-photo/photo-supper-shine-bmw-series-stylish-design_1025753-52413.jpg?w=996",
                            Model = "Volvo",
                            Name = "Foo",
                            Price = 7000m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Color = "Red",
                            CreatedDate = new DateTime(2025, 1, 18, 13, 31, 30, 826, DateTimeKind.Local).AddTicks(9326),
                            ImageUrl = "https://img.freepik.com/premium-photo/photo-supper-shine-bmw-series-stylish-design_1025753-53043.jpg?w=360",
                            Model = "Nissan",
                            Name = "Foo",
                            Price = 1000m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Color = "Black",
                            CreatedDate = new DateTime(2025, 1, 18, 13, 31, 30, 826, DateTimeKind.Local).AddTicks(9329),
                            ImageUrl = "https://img.freepik.com/premium-photo/photo-supper-shine-bmw-series-stylish-design_1025753-52441.jpg?w=360",
                            Model = "Qere",
                            Name = "Foo",
                            Price = 6000m,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
